### PR TITLE
Neka single listing fix module name

### LINKED ISSUE #107: Neka-fix singleListing bug
Fix singleListing bug with faulty file name for styles module

### PR DESCRIPTION
**Pull request by istoga**
## What type of PR is this? (check all applicable)

- [ ] Feature
- [ ] Refactor
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Other (please specify here: <type here>)
  
  
## Description of what this Pull Request does
Rename file for singleListing module

## Related Tickets & Documents
- Closes #107 
- Related Issues: (enter ticket numbers here)
  
## QA Instructions, Screenshots, Recordings
Bug fix only
  
## Added/updated tests?
- [ ] Yes
- [ ] Not Yet, and here is why: __explain here__
- [ ] I need help with tests
- [X] No, and here is why: no testing

### CODE REVIEW

File: src/pages/managerDashboard.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+import FooterBar from '@/components/common/FooterBar';
+import styles from ''../styles/singleListing.module.css';
+
+const managerDashboard = () => {
+  return (
+    <div>managerDashboard</div>
+  )
+}
+
+export default managerDashboard
```
Comment (jjleigh) [inline src/pages/managerDashboard.js:15]: Add a final new line here.

**Review by jjleigh — CHANGES_REQUESTED** [review]
Only a small change request.

The description of the PR states that this is a name change but this PR seems to be doing more than just that. Can you updated the description to explain what is happening here and also add screenshots if applicable.

**Review by ibimina — APPROVED** [review]
LGTM

**Review by jjleigh — APPROVED** [review]
